/**********************************************************************************************************************
 * \file GTM_ATOM_PWM.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "GTM_ATOM_PWM.h"
#include "Ifx_Types.h"
#include "IfxGtm_Atom_Pwm.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ISR_PRIORITY_ATOM  20                                   /* Interrupt priority number                        */
#define LED                IfxGtm_ATOM1_1_TOUT1_P02_1_OUT      /* LED which will be driven by the PWM              */
#define LED2               IfxGtm_ATOM1_3_TOUT105_P10_3_OUT // 이거 추가
#define PWM_PERIOD         330                                 /* PWM period for the ATOM                          */
#define CLK_FREQ           1000000.0f                           /* CMU clock frequency, in Hertz                    */

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxGtm_Atom_Pwm_Config g_atomConfig;                            /* Timer configuration structure                    */
IfxGtm_Atom_Pwm_Driver g_atomDriver;                            /* Timer Driver structure                           */
IfxGtm_Atom_Pwm_Config g_atomConfigB; // 추가
IfxGtm_Atom_Pwm_Driver g_atomDriverB; // 추가
uint32 g_PWMValue = 0;                                         /* Initialization of the fade value                 */

/*********************************************************************************************************************/
/*-----------------------------------------------Function Prototypes-------------------------------------------------*/
/*********************************************************************************************************************/
void setDutyCycle(uint32 dutyCycle);
void setDutyCycleB(uint32 dutyCycle); // 이거 추가
/*********************************************************************************************************************/
/*--------------------------------------------Function Implementations-----------------------------------------------*/
/*********************************************************************************************************************/
/* This function initializes the ATOM */

uint32 TestA = 0; // 테스트용
uint32 TestB = 0;

void initGtmATomPwm(void)
{
    IfxGtm_enable(&MODULE_GTM); /* Enable GTM */

    IfxGtm_Cmu_setClkFrequency(&MODULE_GTM, IfxGtm_Cmu_Clk_0, CLK_FREQ);        /* Set the CMU clock 0 frequency    */
    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_CLK0);                /* Enable the CMU clock 0           */

    IfxGtm_Atom_Pwm_initConfig(&g_atomConfig, &MODULE_GTM);                     /* Initialize default parameters    */

    g_atomConfig.atom = LED.atom;                                       /* Select the ATOM depending on the LED     */
    g_atomConfig.atomChannel = LED.channel;                             /* Select the channel depending on the LED  */
    g_atomConfig.period = PWM_PERIOD;                                   /* Set timer period                         */
    g_atomConfig.pin.outputPin = &LED;                                  /* Set LED as output                        */
    g_atomConfig.synchronousUpdateEnabled = TRUE;                       /* Enable synchronous update                */

    IfxGtm_Atom_Pwm_init(&g_atomDriver, &g_atomConfig);                 /* Initialize the PWM                       */
    IfxGtm_Atom_Pwm_start(&g_atomDriver, TRUE);                         /* Start the PWM                            */

    // 이거 추가
    IfxGtm_Atom_Pwm_initConfig(&g_atomConfigB, &MODULE_GTM);                     /* Initialize default parameters    */

    g_atomConfigB.atom = LED2.atom;                                       /* Select the ATOM depending on the LED     */
    g_atomConfigB.atomChannel = LED2.channel;                             /* Select the channel depending on the LED  */
    g_atomConfigB.period = PWM_PERIOD;                                   /* Set timer period                         */
    g_atomConfigB.pin.outputPin = &LED2;                                  /* Set LED as output                        */
    g_atomConfigB.synchronousUpdateEnabled = TRUE;                       /* Enable synchronous update                */

    IfxGtm_Atom_Pwm_init(&g_atomDriverB, &g_atomConfigB);                 /* Initialize the PWM                       */
    IfxGtm_Atom_Pwm_start(&g_atomDriverB, TRUE);                         /* Start the PWM                            */
}

/* This function is creating the fade effect for the LED */
void PWM_set(uint32 g_PWMValue) // -인지 못함
{
    TestA = g_PWMValue; // ??
    if(g_PWMValue >= PWM_PERIOD)
    {
        g_PWMValue = PWM_PERIOD; /* Set the direction of the fade */
    }
    else if(g_PWMValue <= 0)
    {
        g_PWMValue = 0;  /* Set the direction of the fade */
    }
    setDutyCycle(g_PWMValue); /* Call the function which is setting the duty cycle of the PWM */
}

void PWM_setB(uint32 g_PWMValue)
{
    //TestB = g_PWMValue; // 잘 뜬다.
    if(g_PWMValue >= PWM_PERIOD)
    {
        g_PWMValue = PWM_PERIOD; /* Set the direction of the fade */
    }
    else if(g_PWMValue <= 0)
    {
        g_PWMValue = 0;  /* Set the direction of the fade */
    }
    setDutyCycleB(g_PWMValue); /* Call the function which is setting the duty cycle of the PWM */
}

/* This function sets the duty cycle of the PWM */
void setDutyCycle(uint32 dutyCycle)
{
    g_atomConfig.dutyCycle = dutyCycle;                 /* Set duty cycle        */
    IfxGtm_Atom_Pwm_init(&g_atomDriver, &g_atomConfig); /* Re-initialize the PWM */
}

void setDutyCycleB(uint32 dutyCycle)
{
    g_atomConfigB.dutyCycle = dutyCycle;                 /* Set duty cycle        */
    IfxGtm_Atom_Pwm_init(&g_atomDriverB, &g_atomConfigB); /* Re-initialize the PWM */
}
