/**********************************************************************************************************************
 * \file STM_Interrupt.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef STM_INTERRUPT_H_
#define STM_INTERRUPT_H_
#include "Ifx_Types.h"
#include "PID_CON.h"
#include "Can.h"
/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
// 핀 정의
#define PWMA_PIN &MODULE_P02,1   // PWM 핀 (P2.1)
#define BRAKEA_PIN &MODULE_P02,7 // 브레이크 핀 (P2.7)
#define DIRA_PIN &MODULE_P10,1   // 방향 제어 핀 (P10.1)

// 핀 정의 B 추가
#define PWMB_PIN &MODULE_P10,3   // PWMB 핀 (P10.3)
#define BRAKEB_PIN &MODULE_P02,6 // 브레이크B 핀 (P2.6)
#define DIRB_PIN &MODULE_P10,2   // 방향 제어B 핀 (P10.2)

#define PULSES_PER_REV 330     // 한 채널당 펄스 수 330으로 변경

// 필터 계수
#define FILTER_SIZE 5  // 최근 5개 데이터를 사용

void initIncrEnc(void);
void initIncrEncB(void);
void setMotorControl(uint8 direction, uint8 enable);
void setMotorControlB(uint8 direction, uint8 enable);

void RPM_cal(void);
void PI_const_update(void);
void isrSTM(void);

void goStraight(float32 speed);
void goBackward(float32 speed);
void stopMotors(void);
void calculate_motor_speeds(float32 steering_angle, float32 *left_rpm, float32 *right_rpm);
void setSteeringControl(float32 steeringAngle);

void update_motor_rpm(Message_Info* msgptr);

float32 updateSpeedFilter(float32 newSpeed);
float32 updateSpeedFilterB(float32 newSpeed);
#endif /* STM_INTERRUPT_H_ */
